import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1782,height:1024}});
const page=await context.newPage(), errors=[];page.on('pageerror',e=>errors.push(e.message));
const base='http://127.0.0.1:3000';
try{
 await page.goto(base+'/?verify=restored#/masters');await page.locator('.polaroid').first().waitFor();
 assert.equal(await page.locator('.polaroid').count(),10);
 const first=page.locator('.polaroid').first();const before=await first.getAttribute('style');await page.waitForFunction(s=>document.querySelector('.polaroid').getAttribute('style')!==s,before);
 assert.equal(await page.locator('.polaroid__cap').first().evaluate(e=>getComputedStyle(e).color),'rgb(255, 255, 255)');
 const geometry=await page.evaluate(()=>{const menu=document.querySelector('.menu').getBoundingClientRect(),rent=document.querySelector('.rent-place').getBoundingClientRect(),login=document.querySelector('.login').getBoundingClientRect();return {menu:menu.x,rent:rent.x,login:login.x,rentRight:rent.right,loginRight:login.right,menuRight:menu.right,overflow:[...document.querySelectorAll('.login__links a')].some(e=>e.getBoundingClientRect().right>login.right)}});
 assert.ok(geometry.rent>geometry.menu+100);assert.equal(geometry.rent,geometry.login);assert.ok(Math.abs(geometry.rentRight-geometry.menuRight)<1);assert.equal(geometry.overflow,false);
 await page.screenshot({path:'work/restored-home.png',fullPage:true,animations:'disabled'});
 await first.focus();await page.keyboard.press('Enter');await page.locator('#worksPane').waitFor();await page.screenshot({path:'work/restored-master.png',fullPage:true,animations:'disabled'});
 await page.goto(base+'/#/signup/master');await page.getByLabel('Как вас зовут').fill('Тестовый мастер');await page.getByLabel('Почта для входа и чеков').fill('restored-'+Date.now()+'@example.invalid');await page.getByLabel('Пароль',{exact:true}).fill('Browser-test-password-2026');await page.locator('input[name=rules]').check();await page.locator('input[name=consent]').check();await page.getByRole('button',{name:'Создать личное дело →'}).click();await page.locator('#logout').waitFor();
 await page.getByRole('link',{name:'Rent a place',exact:true}).click();const d=new Date(Date.now()+3*86400000).toISOString().slice(0,10);await page.locator(`[data-day="${d}"]`).click();await page.screenshot({path:'work/restored-booking.png',fullPage:true,animations:'disabled'});await page.locator('#booking-next').click();await page.locator('[data-hour]:not([disabled])').first().click();await page.locator('[data-resource]:not([disabled])').first().click();await page.locator('#booking-next').click();await page.locator('#booking-next').click();await page.locator('#booking-agree').check();await page.locator('#booking-next').click();await page.locator('#test-pay').click();await page.getByText('Подтверждено',{exact:true}).waitFor();await page.locator('[data-cancel]').click();await page.locator('#confirm-cancel').click();await page.getByText('В вашем календаре пока тихо.').waitFor();assert.ok((await page.locator('.stat').first().innerText()).includes('500'));
 await page.locator('#logout').click();await page.getByRole('link',{name:'as tattoo master',exact:true}).waitFor();await page.getByRole('link',{name:'as tattoo master',exact:true}).click();
 const env=Object.fromEntries(readFileSync('work/preview.env','utf8').trim().split('\n').map(x=>{const i=x.indexOf('=');return[x.slice(0,i),x.slice(i+1)];}));await page.getByLabel('Почта для входа и чеков').fill(env.ADMIN_EMAIL);await page.getByLabel('Пароль',{exact:true}).fill(env.ADMIN_PASSWORD);await page.getByRole('button',{name:'Войти →',exact:true}).click();await page.getByRole('link',{name:'Управление сайтом',exact:true}).click();await page.locator('#manual-booking').waitFor();await page.screenshot({path:'work/restored-admin.png',fullPage:true,animations:'disabled'});
 await page.getByRole('button',{name:'Люди',exact:true}).click();await page.locator('#add-user').click();assert.deepEqual(await page.locator('#dialog-form [name=role] option').evaluateAll(x=>x.map(e=>e.value)),['resident','guest','admin']);await page.locator('#dialog .close').click();await page.getByRole('button',{name:'Настройки',exact:true}).click();await page.getByRole('button',{name:'Сохранить настройки',exact:true}).click();await page.getByText('Настройки студии сохранены',{exact:true}).waitFor();
 await page.setViewportSize({width:390,height:844});await page.goto(base+'/?mobile=restored#/masters');await page.locator('.polaroid').first().waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile overflow');await page.screenshot({path:'work/restored-mobile.png',fullPage:true,animations:'disabled'});await page.getByRole('link',{name:'Rent a place',exact:true}).click();await page.locator('.calendar').waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile booking overflow');await page.screenshot({path:'work/restored-booking-mobile.png',fullPage:true,animations:'disabled'});
 assert.deepEqual(errors,[]);console.log('PASS: original Claude shell, flying portraits, XP labels, sidebar alignment, original master page, booking/payment/cancellation, full-access operator, mobile, zero page errors');
} catch(e){await page.screenshot({path:'work/browser-failure.png',fullPage:true});throw e;}finally{await browser.close();}
